### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by jw3126** [gridap/GridapMakie.jl#1]
Here is my vision for what `GridapMakie` should look like:
## Long term
Given any `Gridap` object that has a meaningful graphical representation (`FeFunction`, model, vector field, basis function...)
one should be able to do
```julia
using GridapMakie
plot(model)  # plots a wireframe
plot(u)          # plots a quiver, lines, wireframe + mesh depending on valuetype and space dimension etc.
plot(...)         # plots something reasonable
```
Slightly lower level one should be able to do things like
```julia
quiver(u)
lines(u)
mesh(u)
wireframe(u, color=black, some_more=keywords)
...
```
## Short term
Focus on plotting of `SingleFieldFEFunction` 1d and 2d with triangle cells. 

## Implementation
Dispatch pipeline would look something like this:
```julia
AbstractPlotting.convert_arguments(p::Arrows, visdata::VisualizationData) = ...
AbstractPlotting.convert_arguments(p::Mesh, visdata::VisualizationData) = ...
AbstractPlotting.convert_arguments(p::Wireframe, visdata::VisualizationData) = ...
...

struct FeFunctionPlot 
...
end

function AbstractPlotting.plot(::Plot(FeFunctionPlot))
      # dispatch on space dimension and value_type
      # build plot out of the primitives defined above. 
      # E.g. for a 2d scalar field, use mesh + wireframe with heat map like coloring
      # for 1d scalar field use lines

end

# rewire plot(f::SingleFieldFEFunction) to FeFunctionPlot(visualization_data(f))
```

**Comment by fverdugo** [comment]
Hi @jw3126! I hope you are doing well.

In Gridap, we plan to participate in Google Summer of code. One of the project ideas we want to propose is to further develop GridapMakie.

 If you want to participate let us know. You can participate as a mentor (the project will have a total of 2-3 mentors).

If you can't or don't want to participate is also fine.

**Comment by jw3126** [comment]
Hi @fverdugo I love the idea of making this a GSOCproject. Yeah I am doing well. Sadly my Gridap related project has very low priority and I don't think this will change forseeable future.

I could help with Makie related questions, but I have little knowledge about the Gridap side.
So if the other mentors are strong on Gridap, but new to Makie, it makes sense for me to join. Otherwise, if you are covered on the Makie side already, I think it does not make much sense for me to join.

**Comment by fverdugo** [comment]
Nice to hear about you @jw3126 !

I will be the other mentor. 

If you can join, it would be nice since the student can ask me about Gridap and you about Makie. In any case,  I also plan to learn more about Makie.

I expect that the project would require some coordination. Like a kick-off meeting, and some follow-up meetings, but this is to be defined.

**Comment by jw3126** [comment]
Ok great. Yeah I think what you suggest makes sense and I am happy to join. Maybe we should choose some communication channel for this? Like in Gridap gitter or julia slack? Just pick something and invite me.

**Comment by fverdugo** [comment]
Perfect! I'll invite you to our Gridap slack workspace (this is how we plan to communicate with the students).

**Comment by fverdugo** [comment]
I have sent you the invitation via Gitter.

**Comment by amartinhuertas** [comment]
We are about to release a new/updated version of GridapMakie, with a revamped high level API ... closing the issue
