### ISSUE TITLE
Readme examples don't work

### ISSUE THREAD

**Issue by Sov-trotter** [gridap/GridapMakie.jl#15]
Looks the the examples in the readme don't seem to work
```
ERROR: MethodError: no method matching FESpace(; reffe=:Lagrangian, order=1, valuetype=Float64, conformity=:H1, model=UnstructuredDiscreteModel())

```

**Comment by fverdugo** [comment]
Hi @Sov-trotter Thanks for noting. The package is not maintained now. So, the README.md cannot be trusted  for the moment.

**Comment by amartinhuertas** [comment]
We are about to release a new/updated version of GridapMakie ... closing the issue
