### ISSUE TITLE
Unable to add GridapMakie on MacOS monterey with M1 chip and Julia 1.8.2 

### ISSUE THREAD

**Issue by 55113110039** [gridap/GridapMakie.jl#63]
The error says:

Precompiling project...
  ✗ GridapMakie
  0 dependencies successfully precompiled in 17 seconds. 332 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

GridapMakie [41f30b06-6382-4b60-a5f7-79d86b35bf5d]

Failed to precompile GridapMakie [41f30b06-6382-4b60-a5f7-79d86b35bf5d] to /Users/dap/.julia/compiled/v1.8/GridapMakie/jl_NMTS23.
ERROR: LoadError: UndefVarError: point_iterator not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ ~/.julia/packages/GridapMakie/oS6vj/src/recipes.jl:158
 [3] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [4] include(x::String)
   @ GridapMakie ~/.julia/packages/GridapMakie/oS6vj/src/GridapMakie.jl:1
 [5] top-level scope
   @ ~/.julia/packages/GridapMakie/oS6vj/src/GridapMakie.jl:17
 [6] include
   @ ./Base.jl:419 [inlined]
 [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [8] top-level scope
   @ stdin:1
in expression starting at /Users/dap/.julia/packages/GridapMakie/oS6vj/src/recipes.jl:158
in expression starting at /Users/dap/.julia/packages/GridapMakie/oS6vj/src/GridapMakie.jl:1
in expression starting at stdin:1

**Comment by fverdugo** [comment]
Hi @55113110039 

Try to update to Makie 0.17. See issue #62

**Comment by 55113110039** [comment]
Thank you @fverdugo! Now the compilation passes with Makie@0.17.
