### ISSUE TITLE
GridapMakie seems outdated

### ISSUE THREAD

**Issue by eschnett** [gridap/GridapMakie.jl#70]
GridapMakie's `Project.toml` declarations refer to quite old version of some packages (e.g. `FillArrays`, `Makie`, `CairoMakie`). In addition, trying to use it results in an error:
```Julia
julia> using GridapMakie
Precompiling GridapMakie
        Info Given GridapMakie was explicitly requested, output will be shown live
ERROR: LoadError: UndefVarError: `point_iterator` not defined
```

(This is with Julia 1.10.)

**Comment by rveltz** [comment]
Hi,

I have tried to solve it myself but did not succeed. Can you please resurrect this very useful package?

**Comment by JordiManyer** [comment]
@ovanvincq has a branch going on. Is it functinal? If so, I'm happy to accept a PR and merge the changes for everyone.

**Comment by JordiManyer** [comment]
Actually I'm blind, there is a PR already, see #73

**Comment by JordiManyer** [comment]
The PR has been merged, and it seems like the tests pass. I'll do the next release some day next week (once we fix the small issue we are having with the documenter keys).
